/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze-progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Progression Endpoint */
        post: operations["analyze_progression_endpoint_analyze_progression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain-transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Transition Endpoint */
        get: operations["explain_transition_endpoint_explain_transition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db Check */
        get: operations["health_db_check_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/redis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Redis Check */
        get: operations["health_redis_check_health_redis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/next-chords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Chords Endpoint */
        get: operations["next_chords_endpoint_next_chords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transition-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transition Stats Endpoint */
        get: operations["transition_stats_endpoint_transition_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze-progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Progression Endpoint */
        post: operations["analyze_progression_endpoint_v1_analyze_progression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain-transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Transition Endpoint */
        get: operations["explain_transition_endpoint_v1_explain_transition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/next-chords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Chords Endpoint */
        get: operations["next_chords_endpoint_v1_next_chords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transition-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transition Stats Endpoint */
        get: operations["transition_stats_endpoint_v1_transition_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Endpoint */
        post: operations["analyze_endpoint_v2_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/color/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Color Compare */
        get: operations["color_compare_v2_color_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/color/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Color Profile */
        post: operations["color_profile_v2_color_profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_v2_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/graph/explain-edge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Edge */
        get: operations["explain_edge_v2_graph_explain_edge_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/graph/neighborhood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Neighborhood */
        get: operations["neighborhood_v2_graph_neighborhood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/graph/node/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph Node */
        get: operations["graph_node_v2_graph_node__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/graph/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Graph Path */
        post: operations["graph_path_v2_graph_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_v2_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v2_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_v2_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Events */
        get: operations["get_job_events_v2_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_v2_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/recommend-next-chords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend Next Chords */
        post: operations["recommend_next_chords_v2_recommend_next_chords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/similar-chords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Similar Chords */
        post: operations["similar_chords_v2_similar_chords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/similar-functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Similar Functions */
        post: operations["similar_functions_v2_similar_functions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/similar-progressions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Similar Progressions */
        post: operations["similar_progressions_v2_similar_progressions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisV2 */
        AnalysisV2: {
            /** Ambiguous */
            ambiguous: boolean;
            /** Chords */
            chords: components["schemas"]["CanonicalChord"][];
            /** Key Distribution */
            key_distribution: components["schemas"]["KeyProbability"][];
            /** Local Keys */
            local_keys: string[];
            /** Modulations */
            modulations?: components["schemas"]["Modulation"][];
            /** Relationships */
            relationships?: components["schemas"]["RelationshipFact"][];
            /** Song Key */
            song_key: string;
            /** Tokens */
            tokens: components["schemas"]["RomanToken"][];
            /** Warnings */
            warnings?: components["schemas"]["AnalysisWarning"][];
        };
        /** AnalysisWarning */
        AnalysisWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Raw Value */
            raw_value?: string | null;
            /** Token Index */
            token_index?: number | null;
        };
        /** AnalyzeProgressionRequest */
        AnalyzeProgressionRequest: {
            /** Chords */
            chords: string[];
            /** Genre */
            genre?: string | null;
            /** Key */
            key?: string | null;
            /** Section */
            section?: string | null;
        };
        /** AnalyzeProgressionResponse */
        AnalyzeProgressionResponse: {
            /** Absolute Chords */
            absolute_chords: string[];
            /**
             * Ambiguous
             * @default false
             */
            ambiguous: boolean;
            /** Confidence */
            confidence: number;
            /** Detected Key */
            detected_key: string;
            /** Relationships */
            relationships?: components["schemas"]["TransitionRecord"][];
            /** Roman Chords */
            roman_chords: string[];
            /** Warnings */
            warnings?: components["schemas"]["ParseWarning"][];
        };
        /** AnalyzeV2Request */
        AnalyzeV2Request: {
            /** Chords */
            chords: string | string[];
            /** Key */
            key?: string | null;
            /**
             * Section Markers
             * @default false
             */
            section_markers: boolean;
        };
        /** ArcPoint */
        ArcPoint: {
            /** Chord */
            chord: string;
            /** Perceptual */
            perceptual: {
                [key: string]: components["schemas"]["PerceptualAxisOut"];
            };
            /** Position */
            position: number;
            /** Raw */
            raw: {
                [key: string]: number | null;
            };
            /** Token */
            token: string;
        };
        /** CanonicalChord */
        CanonicalChord: {
            /** Bass */
            bass?: string | null;
            /** Bass Pc */
            bass_pc?: number | null;
            /** Extensions */
            extensions?: string[];
            /** Interval Vector */
            interval_vector?: number[];
            /** Intervals */
            intervals?: number[];
            /** Inversion */
            inversion?: ("root" | "first" | "second" | "third" | "other") | null;
            /** Pc Set Mask */
            pc_set_mask?: number | null;
            /** Pitch Classes */
            pitch_classes?: number[];
            /** Quality */
            quality: string;
            /** Quality Class */
            quality_class?: string | null;
            /** Raw Symbol */
            raw_symbol: string;
            /** Root */
            root: string;
            /** Root Pc */
            root_pc?: number | null;
            /** Symbol */
            symbol: string;
            /** Tones Spelled */
            tones_spelled?: string[];
            /** Warnings */
            warnings?: components["schemas"]["ParseWarning"][];
        };
        /** ColorCompareResponse */
        ColorCompareResponse: {
            a: components["schemas"]["ColorProfileResponse"];
            b: components["schemas"]["ColorProfileResponse"];
            /** Perceptual Deltas */
            perceptual_deltas: {
                [key: string]: number;
            };
            /** Raw Deltas */
            raw_deltas: {
                [key: string]: number;
            };
        };
        /** ColorFilter */
        ColorFilter: {
            /**
             * Axis
             * @enum {string}
             */
            axis: "tension" | "stability" | "chromaticity" | "brightness" | "surprise" | "smoothness" | "complexity" | "resolution" | "finality";
            /**
             * Max
             * @default 1
             */
            max: number;
            /**
             * Min
             * @default 0
             */
            min: number;
        };
        /** ColorProfileRequest */
        ColorProfileRequest: {
            /** Key */
            key?: string | null;
            /** Progression */
            progression: string | string[];
        };
        /** ColorProfileResponse */
        ColorProfileResponse: {
            /** Arc */
            arc: components["schemas"]["ArcPoint"][];
            /** Drivers */
            drivers: components["schemas"]["Driver"][];
            /** Key */
            key: string;
            summary: components["schemas"]["ColorSummary"];
        };
        /** ColorSummary */
        ColorSummary: {
            /** Perceptual */
            perceptual: {
                [key: string]: components["schemas"]["PerceptualAxisOut"];
            };
            /** Raw */
            raw: {
                [key: string]: number;
            };
        };
        /** Driver */
        Driver: {
            /** Chord */
            chord: string;
            /** Position */
            position: number;
            /**
             * Reason
             * @enum {string}
             */
            reason: "final_cadence" | "borrowed_chord" | "chromatic_chord";
            /** Weight */
            weight: number;
        };
        /** EmbeddingRebuildPayload */
        EmbeddingRebuildPayload: {
            /** Corpus Version */
            corpus_version: string;
        };
        /** EmbeddingRebuildRequest */
        EmbeddingRebuildRequest: {
            payload: components["schemas"]["EmbeddingRebuildPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "embedding_rebuild";
        };
        /** EvaluationRunPayload */
        EvaluationRunPayload: {
            /**
             * Song Limit
             * @default 100
             */
            song_limit: number;
            /**
             * Suite
             * @enum {string}
             */
            suite: "keys" | "labels";
        };
        /** EvaluationRunRequest */
        EvaluationRunRequest: {
            payload: components["schemas"]["EvaluationRunPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "evaluation_run";
        };
        /** Evidence */
        Evidence: {
            /** Contexts */
            contexts: string[];
            /** Count */
            count: number;
            /** Example Refs */
            example_refs: components["schemas"]["ExampleRef"][];
        };
        /** ExampleRef */
        ExampleRef: {
            /** Genre */
            genre?: string | null;
            /** Position */
            position?: number | null;
            /** Section */
            section?: string | null;
            /** Song Id */
            song_id: string;
            /** Spotify Id */
            spotify_id?: string | null;
        };
        /** ExamplesData */
        ExamplesData: {
            /** Context */
            context: string;
            /** Examples */
            examples: components["schemas"]["SongExample"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "pattern" | "transition";
            /** Subject */
            subject: string;
        };
        /** ExamplesMeta */
        ExamplesMeta: {
            /** Corpus Version */
            corpus_version: string;
        };
        /** ExamplesResponse */
        ExamplesResponse: {
            data: components["schemas"]["ExamplesData"];
            meta: components["schemas"]["ExamplesMeta"];
            /**
             * Warnings
             * @default []
             */
            warnings: {
                [key: string]: string;
            }[];
        };
        /** ExplainTransitionResponse */
        ExplainTransitionResponse: {
            /** From Roman */
            from_roman: string;
            /** Labels */
            labels?: string[];
            /** Short Explanation */
            short_explanation: string;
            /** Technical Explanation */
            technical_explanation: string;
            /** To Roman */
            to_roman: string;
        };
        /** GraphRebuildPayload */
        GraphRebuildPayload: {
            /** Corpus Version */
            corpus_version: string;
        };
        /** GraphRebuildRequest */
        GraphRebuildRequest: {
            payload: components["schemas"]["GraphRebuildPayload"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "graph_rebuild";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeyProbability */
        KeyProbability: {
            /** Key */
            key: string;
            /** Probability */
            probability: number;
        };
        /** Modulation */
        Modulation: {
            /** Description */
            description: string;
            /** From Key */
            from_key: string;
            /** Section Index */
            section_index: number;
            /** Semitones */
            semitones: number;
            /** To Key */
            to_key: string;
        };
        /** NextChordsResponse */
        NextChordsResponse: {
            /** Candidates */
            candidates: components["schemas"]["TransitionCandidate"][];
            context_used?: components["schemas"]["app__schemas__harmony__ContextUsed"];
            /**
             * Data Source
             * @default unknown
             */
            data_source: string;
            /**
             * Database Transition Count
             * @default 0
             */
            database_transition_count: number;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /** Input */
            input: string[];
        };
        /** ParseWarning */
        ParseWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Raw Value */
            raw_value?: string | null;
        };
        /** PathRequest */
        PathRequest: {
            /**
             * Constraint
             * @default none
             * @enum {string}
             */
            constraint: "none" | "increasing_chromaticity" | "max_chromaticity";
            /**
             * Context
             * @default global
             */
            context: string;
            /** Edge Types */
            edge_types?: string[] | null;
            /** From */
            from: string;
            /**
             * K
             * @default 3
             */
            k: number;
            /** Max Chromaticity */
            max_chromaticity?: number | null;
            /**
             * Max Len
             * @default 6
             */
            max_len: number;
            /** To */
            to: string;
        };
        /** PerceptualAxisOut */
        PerceptualAxisOut: {
            /** Confidence */
            confidence: number;
            /** Explanation */
            explanation: string;
            /**
             * Source
             * @enum {string}
             */
            source: "rule" | "derived" | "feedback";
            /** Value */
            value: number;
        };
        /** RecommendData */
        RecommendData: {
            /** Input Tokens */
            input_tokens: string[];
            /** Key */
            key: string;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
        };
        /** RecommendMeta */
        RecommendMeta: {
            context_used: components["schemas"]["app__schemas__recommend_v2__ContextUsed"];
            /** Corpus Version */
            corpus_version: string;
            /** Latency Ms */
            latency_ms: number;
            /** Model Versions */
            model_versions: {
                [key: string]: string;
            };
        };
        /** RecommendRequest */
        RecommendRequest: {
            /** Genre */
            genre?: string | null;
            /**
             * Include Explanations
             * @default true
             */
            include_explanations: boolean;
            /** Key */
            key?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Progression */
            progression: string | string[];
            /** Section */
            section?: string | null;
        };
        /** RecommendResponse */
        RecommendResponse: {
            data: components["schemas"]["RecommendData"];
            meta: components["schemas"]["RecommendMeta"];
            /** Warnings */
            warnings?: components["schemas"]["RecommendWarning"][];
        };
        /** RecommendWarning */
        RecommendWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** Recommendation */
        Recommendation: {
            /** Chord */
            chord: string;
            /** Color */
            color?: {
                [key: string]: number;
            };
            evidence: components["schemas"]["Evidence"];
            /** Explanation */
            explanation?: string | null;
            /** Fact Ids */
            fact_ids: string[];
            /** Figure */
            figure: string;
            /** Labels */
            labels: string[];
            /** Score */
            score: number;
            score_breakdown: components["schemas"]["ScoreBreakdown"];
            /** Token */
            token: string;
        };
        /** RelationshipFact */
        RelationshipFact: {
            /**
             * Category
             * @enum {string}
             */
            category: "cadence" | "functional" | "chromatic" | "voice_leading" | "modal";
            /** Fact Ids */
            fact_ids: string[];
            /** From Index */
            from_index: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Short Explanation */
            short_explanation: string;
            /** Technical Explanation */
            technical_explanation: string;
            /** To Index */
            to_index: number;
        };
        /** RomanToken */
        RomanToken: {
            /**
             * Accidental
             * @default
             */
            accidental: string;
            /** Applied Role */
            applied_role?: ("V" | "viio" | "subV") | null;
            /** Applied To */
            applied_to?: string | null;
            /** Bass Pc */
            bass_pc: number;
            /** Borrowed From */
            borrowed_from?: string | null;
            /** Chord Index */
            chord_index: number;
            /** Confidence */
            confidence: number;
            /** Core */
            core: string;
            /** Degree */
            degree: number;
            /** Display Figure */
            display_figure: string;
            /** Extensions */
            extensions?: string[];
            /** Figure */
            figure: string;
            /**
             * Function
             * @default other
             * @enum {string}
             */
            function: "T" | "PD" | "D" | "other";
            /**
             * Inversion
             * @default root
             */
            inversion: string;
            /**
             * Is Borrowed
             * @default false
             */
            is_borrowed: boolean;
            /**
             * Is Chromatic
             * @default false
             */
            is_chromatic: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "major" | "minor";
            /** Pitch Classes */
            pitch_classes?: number[];
            /** Quality Class */
            quality_class: string;
            /** Root Pc */
            root_pc: number;
            /** Tags */
            tags?: string[];
            /**
             * Unresolved
             * @default false
             */
            unresolved: boolean;
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Backoff */
            backoff: number;
            /** Context */
            context: number;
            /** Ngram */
            ngram: number;
        };
        /** SimilarChordRequest */
        SimilarChordRequest: {
            /** Chord */
            chord: string;
            /**
             * K
             * @default 10
             */
            k: number;
        };
        /** SimilarFunctionRequest */
        SimilarFunctionRequest: {
            /**
             * K
             * @default 10
             */
            k: number;
            /** Model */
            model?: ("chord2vec" | "fastrp") | null;
            /** Token */
            token: string;
        };
        /** SimilarItem */
        SimilarItem: {
            /** Rotation Of */
            rotation_of?: string | null;
            /** Shared Tokens */
            shared_tokens?: string[];
            /** Similarity */
            similarity: number;
            /** Subject Id */
            subject_id: string;
            /** Support */
            support?: number | null;
        };
        /** SimilarProgressionRequest */
        SimilarProgressionRequest: {
            filters?: components["schemas"]["SimilarityFilters"];
            /**
             * K
             * @default 10
             */
            k: number;
            /** Key */
            key?: string | null;
            /**
             * Mode
             * @default structural
             * @enum {string}
             */
            mode: "structural" | "surface";
            /** Progression */
            progression?: string | string[] | null;
            /** Tokens */
            tokens?: string[] | null;
        };
        /** SimilarResponse */
        SimilarResponse: {
            /** Corpus Version */
            corpus_version: string;
            /** Model */
            model: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SimilarItem"][];
            /** Warnings */
            warnings?: string[];
        };
        /** SimilarityFilters */
        SimilarityFilters: {
            color?: components["schemas"]["ColorFilter"] | null;
            /** Genre */
            genre?: string | null;
        };
        /** SongExample */
        SongExample: {
            /** Decade */
            decade: string | null;
            /** Genre */
            genre: string | null;
            /** Position */
            position: number | null;
            /** Rank */
            rank: number;
            /** Section */
            section: string | null;
            /** Section Ordinal */
            section_ordinal: number;
            /** Song Id */
            song_id: string;
            /** Spotify Id */
            spotify_id: string | null;
        };
        /** TransitionCandidate */
        TransitionCandidate: {
            /** Chord */
            chord: string;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Probability */
            probability: number;
            /** Relationship */
            relationship?: string | null;
            /** Relationship Labels */
            relationship_labels?: string[];
        };
        /** TransitionRecord */
        TransitionRecord: {
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Decade */
            decade?: number | null;
            /** From Roman */
            from_roman: string;
            /** Genre */
            genre?: string | null;
            /**
             * Mode Context
             * @default unknown
             * @enum {string}
             */
            mode_context: "major" | "minor" | "unknown";
            /**
             * Probability
             * @default 0
             */
            probability: number;
            /** Relationship Labels */
            relationship_labels?: string[];
            /** Section */
            section?: string | null;
            /** Short Explanation */
            short_explanation?: string | null;
            /** Subgenre */
            subgenre?: string | null;
            /** Technical Explanation */
            technical_explanation?: string | null;
            /** To Roman */
            to_roman: string;
        };
        /** TransitionStatsResponse */
        TransitionStatsResponse: {
            context_used?: components["schemas"]["app__schemas__harmony__ContextUsed"];
            /**
             * Data Source
             * @default unknown
             */
            data_source: string;
            /**
             * Database Transition Count
             * @default 0
             */
            database_transition_count: number;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /** From Roman */
            from_roman: string;
            /** Genre */
            genre?: string | null;
            /** Next */
            next?: components["schemas"]["TransitionCandidate"][];
            /** Section */
            section?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ContextUsed */
        app__schemas__harmony__ContextUsed: {
            /** Backoff */
            backoff?: string[];
            /** Genre */
            genre?: string | null;
            /**
             * Mode
             * @default major
             */
            mode: string;
            /** Section */
            section?: string | null;
        };
        /** ContextUsed */
        app__schemas__recommend_v2__ContextUsed: {
            /** Backoff */
            backoff: string[];
            /** Genre */
            genre?: string | null;
            /** Section */
            section?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_progression_endpoint_analyze_progression_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeProgressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeProgressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_transition_endpoint_explain_transition_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_db_check_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_redis_check_health_redis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    next_chords_endpoint_next_chords_get: {
        parameters: {
            query: {
                progression: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextChordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_stats_endpoint_transition_stats_get: {
        parameters: {
            query: {
                from: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_progression_endpoint_v1_analyze_progression_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeProgressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeProgressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_transition_endpoint_v1_explain_transition_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_chords_endpoint_v1_next_chords_get: {
        parameters: {
            query: {
                progression: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextChordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_stats_endpoint_v1_transition_stats_get: {
        parameters: {
            query: {
                from: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_endpoint_v2_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeV2Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    color_compare_v2_color_compare_get: {
        parameters: {
            query: {
                a: string;
                b: string;
                key_a?: string | null;
                key_b?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorCompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    color_profile_v2_color_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColorProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColorProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    examples_v2_examples_get: {
        parameters: {
            query?: {
                pattern_id?: string | null;
                transition?: string | null;
                context?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamplesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_edge_v2_graph_explain_edge_get: {
        parameters: {
            query: {
                src: string;
                dst: string;
                context?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    neighborhood_v2_graph_neighborhood_get: {
        parameters: {
            query: {
                id: string;
                context?: string;
                edge_types?: string | null;
                min_prob?: number;
                limit?: number;
                hops?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_node_v2_graph_node__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_path_v2_graph_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_v2_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "X-HCG-Jobs-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphRebuildRequest"] | components["schemas"]["EmbeddingRebuildRequest"] | components["schemas"]["EvaluationRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v2_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-HCG-Jobs-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_v2_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-HCG-Jobs-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_events_v2_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "X-HCG-Jobs-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_v2_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-HCG-Jobs-Token"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_next_chords_v2_recommend_next_chords_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_chords_v2_similar_chords_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarChordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_functions_v2_similar_functions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarFunctionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_progressions_v2_similar_progressions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarProgressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
