/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze-progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Progression Endpoint */
        post: operations["analyze_progression_endpoint_analyze_progression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain-transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Transition Endpoint */
        get: operations["explain_transition_endpoint_explain_transition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db Check */
        get: operations["health_db_check_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/next-chords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Chords Endpoint */
        get: operations["next_chords_endpoint_next_chords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transition-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transition Stats Endpoint */
        get: operations["transition_stats_endpoint_transition_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analyze-progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Progression Endpoint */
        post: operations["analyze_progression_endpoint_v1_analyze_progression_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/explain-transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explain Transition Endpoint */
        get: operations["explain_transition_endpoint_v1_explain_transition_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/next-chords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Chords Endpoint */
        get: operations["next_chords_endpoint_v1_next_chords_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transition-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transition Stats Endpoint */
        get: operations["transition_stats_endpoint_v1_transition_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Endpoint */
        post: operations["analyze_endpoint_v2_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisV2 */
        AnalysisV2: {
            /** Ambiguous */
            ambiguous: boolean;
            /** Chords */
            chords: components["schemas"]["CanonicalChord"][];
            /** Key Distribution */
            key_distribution: components["schemas"]["KeyProbability"][];
            /** Local Keys */
            local_keys: string[];
            /** Modulations */
            modulations?: components["schemas"]["Modulation"][];
            /** Relationships */
            relationships?: components["schemas"]["RelationshipFact"][];
            /** Song Key */
            song_key: string;
            /** Tokens */
            tokens: components["schemas"]["RomanToken"][];
            /** Warnings */
            warnings?: components["schemas"]["AnalysisWarning"][];
        };
        /** AnalysisWarning */
        AnalysisWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Raw Value */
            raw_value?: string | null;
            /** Token Index */
            token_index?: number | null;
        };
        /** AnalyzeProgressionRequest */
        AnalyzeProgressionRequest: {
            /** Chords */
            chords: string[];
            /** Genre */
            genre?: string | null;
            /** Key */
            key?: string | null;
            /** Section */
            section?: string | null;
        };
        /** AnalyzeProgressionResponse */
        AnalyzeProgressionResponse: {
            /** Absolute Chords */
            absolute_chords: string[];
            /**
             * Ambiguous
             * @default false
             */
            ambiguous: boolean;
            /** Confidence */
            confidence: number;
            /** Detected Key */
            detected_key: string;
            /** Relationships */
            relationships?: components["schemas"]["TransitionRecord"][];
            /** Roman Chords */
            roman_chords: string[];
            /** Warnings */
            warnings?: components["schemas"]["ParseWarning"][];
        };
        /** AnalyzeV2Request */
        AnalyzeV2Request: {
            /** Chords */
            chords: string | string[];
            /** Key */
            key?: string | null;
            /**
             * Section Markers
             * @default false
             */
            section_markers: boolean;
        };
        /** CanonicalChord */
        CanonicalChord: {
            /** Bass */
            bass?: string | null;
            /** Bass Pc */
            bass_pc?: number | null;
            /** Extensions */
            extensions?: string[];
            /** Interval Vector */
            interval_vector?: number[];
            /** Intervals */
            intervals?: number[];
            /** Inversion */
            inversion?: ("root" | "first" | "second" | "third" | "other") | null;
            /** Pc Set Mask */
            pc_set_mask?: number | null;
            /** Pitch Classes */
            pitch_classes?: number[];
            /** Quality */
            quality: string;
            /** Quality Class */
            quality_class?: string | null;
            /** Raw Symbol */
            raw_symbol: string;
            /** Root */
            root: string;
            /** Root Pc */
            root_pc?: number | null;
            /** Symbol */
            symbol: string;
            /** Tones Spelled */
            tones_spelled?: string[];
            /** Warnings */
            warnings?: components["schemas"]["ParseWarning"][];
        };
        /** ContextUsed */
        ContextUsed: {
            /** Backoff */
            backoff?: string[];
            /** Genre */
            genre?: string | null;
            /**
             * Mode
             * @default major
             */
            mode: string;
            /** Section */
            section?: string | null;
        };
        /** ExplainTransitionResponse */
        ExplainTransitionResponse: {
            /** From Roman */
            from_roman: string;
            /** Labels */
            labels?: string[];
            /** Short Explanation */
            short_explanation: string;
            /** Technical Explanation */
            technical_explanation: string;
            /** To Roman */
            to_roman: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeyProbability */
        KeyProbability: {
            /** Key */
            key: string;
            /** Probability */
            probability: number;
        };
        /** Modulation */
        Modulation: {
            /** Description */
            description: string;
            /** From Key */
            from_key: string;
            /** Section Index */
            section_index: number;
            /** Semitones */
            semitones: number;
            /** To Key */
            to_key: string;
        };
        /** NextChordsResponse */
        NextChordsResponse: {
            /** Candidates */
            candidates: components["schemas"]["TransitionCandidate"][];
            context_used?: components["schemas"]["ContextUsed"];
            /**
             * Data Source
             * @default unknown
             */
            data_source: string;
            /**
             * Database Transition Count
             * @default 0
             */
            database_transition_count: number;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /** Input */
            input: string[];
        };
        /** ParseWarning */
        ParseWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Raw Value */
            raw_value?: string | null;
        };
        /** RelationshipFact */
        RelationshipFact: {
            /**
             * Category
             * @enum {string}
             */
            category: "cadence" | "functional" | "chromatic" | "voice_leading" | "modal";
            /** Fact Ids */
            fact_ids: string[];
            /** From Index */
            from_index: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Short Explanation */
            short_explanation: string;
            /** Technical Explanation */
            technical_explanation: string;
            /** To Index */
            to_index: number;
        };
        /** RomanToken */
        RomanToken: {
            /**
             * Accidental
             * @default
             */
            accidental: string;
            /** Applied Role */
            applied_role?: ("V" | "viio" | "subV") | null;
            /** Applied To */
            applied_to?: string | null;
            /** Bass Pc */
            bass_pc: number;
            /** Borrowed From */
            borrowed_from?: string | null;
            /** Chord Index */
            chord_index: number;
            /** Confidence */
            confidence: number;
            /** Core */
            core: string;
            /** Degree */
            degree: number;
            /** Display Figure */
            display_figure: string;
            /** Extensions */
            extensions?: string[];
            /** Figure */
            figure: string;
            /**
             * Function
             * @default other
             * @enum {string}
             */
            function: "T" | "PD" | "D" | "other";
            /**
             * Inversion
             * @default root
             */
            inversion: string;
            /**
             * Is Borrowed
             * @default false
             */
            is_borrowed: boolean;
            /**
             * Is Chromatic
             * @default false
             */
            is_chromatic: boolean;
            /**
             * Mode
             * @enum {string}
             */
            mode: "major" | "minor";
            /** Pitch Classes */
            pitch_classes?: number[];
            /** Quality Class */
            quality_class: string;
            /** Root Pc */
            root_pc: number;
            /** Tags */
            tags?: string[];
            /**
             * Unresolved
             * @default false
             */
            unresolved: boolean;
        };
        /** TransitionCandidate */
        TransitionCandidate: {
            /** Chord */
            chord: string;
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Probability */
            probability: number;
            /** Relationship */
            relationship?: string | null;
            /** Relationship Labels */
            relationship_labels?: string[];
        };
        /** TransitionRecord */
        TransitionRecord: {
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Decade */
            decade?: number | null;
            /** From Roman */
            from_roman: string;
            /** Genre */
            genre?: string | null;
            /**
             * Mode Context
             * @default unknown
             * @enum {string}
             */
            mode_context: "major" | "minor" | "unknown";
            /**
             * Probability
             * @default 0
             */
            probability: number;
            /** Relationship Labels */
            relationship_labels?: string[];
            /** Section */
            section?: string | null;
            /** Short Explanation */
            short_explanation?: string | null;
            /** Subgenre */
            subgenre?: string | null;
            /** Technical Explanation */
            technical_explanation?: string | null;
            /** To Roman */
            to_roman: string;
        };
        /** TransitionStatsResponse */
        TransitionStatsResponse: {
            context_used?: components["schemas"]["ContextUsed"];
            /**
             * Data Source
             * @default unknown
             */
            data_source: string;
            /**
             * Database Transition Count
             * @default 0
             */
            database_transition_count: number;
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /** From Roman */
            from_roman: string;
            /** Genre */
            genre?: string | null;
            /** Next */
            next?: components["schemas"]["TransitionCandidate"][];
            /** Section */
            section?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_progression_endpoint_analyze_progression_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeProgressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeProgressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_transition_endpoint_explain_transition_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_db_check_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    next_chords_endpoint_next_chords_get: {
        parameters: {
            query: {
                progression: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextChordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_stats_endpoint_transition_stats_get: {
        parameters: {
            query: {
                from: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_progression_endpoint_v1_analyze_progression_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeProgressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeProgressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_transition_endpoint_v1_explain_transition_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainTransitionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_chords_endpoint_v1_next_chords_get: {
        parameters: {
            query: {
                progression: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextChordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_stats_endpoint_v1_transition_stats_get: {
        parameters: {
            query: {
                from: string;
                mode?: string;
                genre?: string | null;
                section?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_endpoint_v2_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeV2Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
