import Link from "next/link"
import { RouteMotif } from "@/components/studio-primitives"

export default function AboutPage() {
  return <main id="main-content" className="about-studio studio-page"><header><p className="route-eyebrow">Harmonic Color Graph</p><h1>A place to follow your ear.</h1><p>Write with chords. Explore their relationships. Keep the musical decisions yours.</p><RouteMotif /></header>
    <ol className="onboarding-sequence"><li><span>01</span><h2>Bring a starting point</h2><p>Paste chords, choose a feeling, or try a small loop. Feelings set editable parameters; they are suggestions, not universal emotional meanings.</p></li><li><span>02</span><h2>Hear one change</h2><p>Analyze your sketch, listen, then compare a next chord. Keep promising alternatives as named variations.</p></li><li><span>03</span><h2>Trace a relationship</h2><p>Follow a directed route in the atlas. Inspect its evidence or prepare a reproducible teaching view.</p></li></ol>
    <section className="model-definitions"><h2>Reading the music</h2><dl><dt>Harmonic color</dt><dd>Descriptive measures such as chromaticity and tension summarize musical features. The chosen tint maps a measure to color; it is not a claim that a hue causes a feeling.</dd><dt>Graph position</dt><dd>A deterministic relationship layout arranges connected nodes in 3D. Distance is not a musical similarity score. Orbit changes your viewpoint, not the harmonic data.</dd><dt>Probability and support</dt><dd>When available, probabilities describe observed corpus transitions in a stated context. Counts describe supporting observations. Neither guarantees what a listener will like.</dd><dt>Sample atlas</dt><dd>When the database is unavailable, the bundled sample demonstrates relationships. It does not supply live corpus counts or context-specific evidence.</dd></dl></section>
    <section><h2>Choose your workspace</h2><div className="audience-links"><Link href="/">Songwriters → Write music</Link><Link href="/explore">Education teams → Explore and present</Link></div><p>Saved sketches are local to your browser. Export a backup for portability. Shared teaching views contain a captured graph and explanation, not classroom accounts or a platform integration.</p></section>
    <section><h2>Data & limitations</h2><p>Chord data: <a href="https://arxiv.org/abs/2410.22046">Chordonomicon (Kantarelis et al., 2024)</a>, licensed <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>. Corpus coverage and annotations shape every supported statistic. Analysis can be ambiguous; compare interpretations and use your ear.</p><p>The Assistant uses available tools and cited facts. Check its evidence before relying on an explanation. Unavailable data is labeled rather than replaced with invented results.</p></section>
  </main>
}
