import { expect, test } from "@playwright/test"
import { parseTeachingHash } from "../../lib/graph/presentation"

const book = async (page: import("@playwright/test").Page) => page.evaluate(() => JSON.parse(localStorage.getItem("hcg.sketchbook.v1")!))
test("named sections, independent variations, undo and full backup survive navigation and reload", async ({ page }) => {
  await page.goto("/?p=Am-F-C&k=A-minor&g=jazz&s=verse")
  await page.getByLabel("Sketch name", { exact: true }).fill("Midnight colors")
  await page.getByLabel("Sketch name", { exact: true }).blur()
  await page.getByLabel("Chord progression", { exact: true }).fill("Am, F, C")
  await page.getByRole("button", { name: "+ Section", exact: true }).click()
  await page.getByLabel("Chord progression", { exact: true }).fill("Dm - G - C")
  await page.getByLabel("Key (optional)").fill("D minor")
  await page.getByLabel("Section", { exact: true }).selectOption("chorus")
  await page.locator(".sketch-library > summary").click()
  await page.getByLabel("Section label").fill("Chorus")
  await page.getByLabel("Section label").blur()
  await page.getByRole("button", { name: "Save snapshot", exact: true }).click()
  const first = await book(page)
  await page.getByRole("button", { name: "Save variation", exact: true }).click()
  await page.getByLabel("Chord 1", { exact: true }).fill("E7")
  await page.getByLabel("Chord 1", { exact: true }).blur()
  await page.getByRole("button", { name: "Undo", exact: true }).click()
  await expect(page.getByLabel("Chord 1", { exact: true })).toHaveValue("Dm")
  const variant = await book(page)
  expect(variant.draft.id).not.toBe(first.draft.id)
  expect(variant.draft.parentId).toBe(first.draft.id)
  expect(variant.saved.find((s: {id: string}) => s.id === first.draft.id)).toEqual(first.saved[0])
  await page.getByRole("group", { name: "Song sections" }).getByRole("button", { name: "verse", exact: true }).click()
  await page.reload()
  await expect(page.getByLabel("Sketch name", { exact: true })).toHaveValue("Midnight colors · variation")
  await expect(page.getByLabel("Chord progression", { exact: true })).toHaveValue("Am, F, C")
  await expect(page.getByRole("group", { name: "Song sections" }).getByRole("button", { name: "Chorus", exact: true })).toBeVisible()
  await page.locator(".sketch-library > summary").click()
  const download = page.waitForEvent("download")
  await page.getByRole("button", { name: "Export backup", exact: true }).click()
  const backup = await (await download).path()
  await page.getByRole("button", { name: "New draft", exact: true }).click()
  await page.getByLabel("Import backup").setInputFiles(backup!)
  await expect(page.getByText("Backup imported as separate copies", { exact: false })).toBeVisible()
  expect((await book(page)).saved.length).toBe(4)
  await page.reload()
  expect((await book(page)).draft.sections.length).toBe(2)
})

test("a teaching view opens offline in a fresh context with the captured camera and exact route", async ({ page, browser }) => {
  const nodes = ["I", "IV", "bVI"].map((figure) => ({ id: `function:M:${figure}`, type: "function", label: figure, props: {} }))
  const edges = [{ src: nodes[0].id, dst: nodes[1].id, type: "TRANSITIONS_TO", context_id: 7, prob: .7, count: 20, props: {} }, { src: nodes[1].id, dst: nodes[2].id, type: "TRANSITIONS_TO", context_id: 7, prob: .6, count: 12, props: {} }]
  await page.route("**/api/hcg/v2/graph/neighborhood?**", (route) => route.fulfill({ json: { data: { nodes, edges: [...edges, { ...edges[0], context_id: 8 }], context: "global" } } }))
  await page.route("**/api/hcg/v2/graph/path", (route) => route.fulfill({ json: { data: { paths: [{ nodes: nodes.map((n) => n.id), edges, cost: 1 }] } } }))
  await page.goto("/explore?p=Am-F-C&k=A-minor&g=jazz&s=verse")
  await expect(page.locator(".atlas-canvas")).toHaveAttribute("data-rendering", "paused")
  await page.getByRole("button", { name: "Find paths", exact: true }).click()
  await page.getByRole("list", { name: "Route steps" }).getByRole("button").nth(1).click()
  await page.getByText("Graph filters & color").click()
  await page.getByLabel("Node tint").selectOption("tension")
  await page.getByRole("button", { name: "Zoom in", exact: true }).click()
  await expect(page.locator(".atlas-canvas")).toHaveAttribute("data-rendering", "paused")
  await page.getByText("Prepare a teaching view", { exact: true }).click()
  await page.getByLabel("Presentation title").fill("Night colors: a directed route")
  await page.getByLabel("Your explanation").fill("<script>not executable</script> Notice the borrowed destination.")
  await page.getByRole("button", { name: "Capture teaching view", exact: true }).click()
  const link = await page.getByLabel("Prepared link").inputValue()
  const captured = parseTeachingHash(new URL(link).hash)
  expect(captured.path?.edges.map((e) => e.context_id)).toEqual([7, 7])
  expect(captured.selected).toBe(nodes[1].id)
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const fresh = await context.newPage()
  await fresh.route("**/api/hcg/**", (route) => route.abort())
  await fresh.goto(link)
  await expect(fresh.getByRole("heading", { name: "Night colors: a directed route" })).toBeVisible()
  await expect(fresh.locator(".atlas-canvas")).toHaveAttribute("data-rendering", "paused")
  const positions = JSON.parse(await fresh.locator(".atlas-canvas").getAttribute("data-positions") ?? "[]")
  expect(positions).toEqual(captured.view!.positions)
  const camera = JSON.parse(await fresh.locator(".atlas-canvas").getAttribute("data-camera") ?? "{}")
  expect(camera).toMatchObject(captured.view!.camera.position)
  await expect(fresh.getByRole("list", { name: "Route steps" }).getByRole("button").nth(1)).toHaveAttribute("aria-pressed", "true")
  await expect(fresh.getByText("<script>not executable</script> Notice the borrowed destination.")).toBeVisible()
  expect(await fresh.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
  await fresh.getByRole("button", { name: "List view", exact: true }).click()
  await expect(fresh.getByRole("table").locator("tbody tr")).toHaveCount(3)
  await fresh.emulateMedia({ media: "print" })
  await expect(fresh.locator(".print-route")).toBeVisible()
  await expect(fresh.locator(".print-only")).toContainText("Selected: IV")
  await context.close()
})

test("malformed teaching links offer recovery without backend or local state", async ({ page }) => {
  await page.goto("/teach#view=invalid!")
  await expect(page.getByRole("heading", { name: "Open a teaching view" })).toBeVisible()
  await expect(page.getByLabel("Teaching view JSON")).toBeVisible()
  await expect(page.getByRole("link", { name: "Prepare a new view in the atlas" })).toBeVisible()
})
