"use client"
import { useState } from "react"
import { downloadJSON, newSketch, parseSketchBook } from "@/lib/sketches"
import type { useSketchbook } from "@/lib/hooks/use-sketchbook"

export function SketchEditor({ store, busy }: { store: ReturnType<typeof useSketchbook>; busy: boolean }) {
  const [message, setMessage] = useState("")
  const [remove, setRemove] = useState("")
  const { draft, book } = store
  if (!draft || !book) return <p role="status">Opening your sketch…</p>
  const current = draft.sections.find((section) => section.id === draft.activeSection)!
  const tokens = current.music.input.split(/\s*-\s*|\s*,\s*|\r?\n+|\s+/).filter(Boolean)
  function updateTokens(next: string[]) { store.editMusic({ ...current.music, input: next.join(" - ") }) }
  function move(index: number, offset: number) { const next = [...tokens]; [next[index], next[index + offset]] = [next[index + offset], next[index]]; updateTokens(next) }
  return <section className="sketch-editor" aria-label="Sketch editor">
    <div className="sketch-title-row"><label>Sketch name<input key={`${draft.id}:${draft.name}`} defaultValue={draft.name} maxLength={80} onBlur={(event) => store.change({ ...draft, name: event.target.value.trim() || "Untitled sketch" })} /></label><div className="action-row"><button type="button" onClick={store.undo} disabled={!store.canUndo}>Undo</button><button type="button" onClick={store.redo} disabled={!store.canRedo}>Redo</button><button type="submit" form="sketch-analysis" disabled={busy} className="sketch-analyze">Analyze</button></div></div>
    <div className="section-tabs" role="group" aria-label="Song sections">{draft.sections.map((section) => <button key={section.id} type="button" aria-pressed={section.id === draft.activeSection} onClick={() => store.change({ ...draft, activeSection: section.id })}>{section.name}</button>)}<button type="button" disabled={draft.sections.length >= 24} onClick={() => { const id = crypto.randomUUID(); store.change({ ...draft, activeSection: id, sections: [...draft.sections, { id, name: `Section ${draft.sections.length + 1}`, music: { ...current.music, input: "", section: "" } }] }) }}>+ Section</button></div>
    <div className="chord-strip" role="group" aria-label="Editable chords">{tokens.map((token, index) => <div className="chord-tile" key={index}><label><span>Chord {index + 1}</span><input aria-label={`Chord ${index + 1}`} key={token} defaultValue={token} maxLength={40} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur() }} onBlur={(event) => { const value = event.target.value.trim(); if (value && value !== token) updateTokens(tokens.map((item, i) => i === index ? value : item)); else event.target.value = token }} /></label><div><button type="button" aria-label={`Move chord ${index + 1} earlier`} disabled={!index} onClick={() => move(index, -1)}>←</button><button type="button" aria-label={`Move chord ${index + 1} later`} disabled={index === tokens.length - 1} onClick={() => move(index, 1)}>→</button><button type="button" aria-label={`Remove chord ${index + 1}`} onClick={() => updateTokens(tokens.filter((_, i) => i !== index))}>×</button></div></div>)}<button type="button" onClick={() => updateTokens([...tokens, "C"])}>+ Chord</button></div>
    <details className="sketch-library"><summary>Sections & saved sketches <span>· stored only on this device</span></summary><div className="studio-stack"><div className="action-row"><button type="button" onClick={() => store.save()}>Save snapshot</button><button type="button" onClick={() => store.save(true)}>Save variation</button></div>
      <label>Section label<input key={`${current.id}:${current.name}`} defaultValue={current.name} maxLength={80} onBlur={(event) => store.change({ ...draft, sections: draft.sections.map((section) => section.id === current.id ? { ...section, name: event.target.value.trim() || "Section" } : section) })} /></label>
      <div className="action-row">{[-1, 1].map((offset) => <button key={offset} type="button" disabled={draft.sections.findIndex((section) => section.id === current.id) + offset < 0 || draft.sections.findIndex((section) => section.id === current.id) + offset >= draft.sections.length} onClick={() => { const index = draft.sections.findIndex((section) => section.id === current.id), next = [...draft.sections]; [next[index], next[index + offset]] = [next[index + offset], next[index]]; store.change({ ...draft, sections: next }) }}>Move section {offset < 0 ? "earlier" : "later"}</button>)}<button type="button" disabled={draft.sections.length === 1} onClick={() => store.change({ ...draft, activeSection: draft.sections.find((section) => section.id !== current.id)!.id, sections: draft.sections.filter((section) => section.id !== current.id) })}>Remove section (undo available)</button><button type="button" onClick={() => store.open(newSketch({ ...current.music, input: "" }))}>New draft</button><button type="button" onClick={() => downloadJSON(book, "harmonic-color-graph-sketchbook.json")}>Export backup</button><label className="file-action">Import backup<input type="file" accept="application/json,.json" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { if (file.size > 2_000_000) throw new Error("File exceeds 2 MB."); const imported = parseSketchBook(await file.text()); store.restoreBackup(imported); setMessage("Backup imported as separate copies, including saved sketches and recovery drafts. Existing work is preserved.") } catch (error) { setMessage(error instanceof Error ? error.message : "Import failed.") } event.target.value = "" }} /></label></div>
      <p>Section labels organize the song; the separate Section filter in musical details controls corpus context. Snapshots preserve every section. Variations are separate copies. Export a backup to move work between devices; clearing browser storage removes local drafts.</p>
      <ul className="saved-sketches">{book.saved.map((sketch) => <li key={sketch.id}><button type="button" onClick={() => store.open(sketch)}><strong>{sketch.name}</strong><span>{sketch.sections.length} section{sketch.sections.length === 1 ? "" : "s"}{sketch.parentId ? " · variation" : ""}</span></button><button type="button" onClick={() => { if (remove === sketch.id) { store.removeSaved(sketch.id); setRemove("") } else setRemove(sketch.id) }}>{remove === sketch.id ? "Confirm remove snapshot" : "Remove snapshot"}</button></li>)}</ul>{!book.saved.length && <p>No saved snapshots yet. Your active draft is saved automatically when storage is available.</p>}
      <details><summary>Recover previous drafts ({book.recoveries.length})</summary><ul className="saved-sketches">{book.recoveries.map((sketch) => <li key={sketch.id}><button type="button" onClick={() => store.open(sketch)}>Recover {sketch.name} · {sketch.sections.length} sections</button><button type="button" onClick={() => { if (remove === sketch.id) { store.removeRecovery(sketch.id); setRemove("") } else setRemove(sketch.id) }}>{remove === sketch.id ? "Confirm remove recovery" : "Remove recovery"}</button></li>)}</ul></details>
    </div></details>
    <p className={store.storageBlocked ? "request-error" : "storage-status"} role="status">{store.status}</p>{message && <p role="status">{message}</p>}
  </section>
}
