"use client"
import { useEffect, useState } from "react"
import dynamic from "next/dynamic"
import Link from "next/link"
import { parseTeachingHash, parseTeachingView, functionExplanation, type TeachingView } from "@/lib/graph/presentation"
import { edgeKey } from "@/lib/graph/data"
import { writeProgression } from "@/lib/progression-url"
import { GraphLegend } from "@/components/graph-legend"
import { ContextSummary, RouteMotif } from "@/components/studio-primitives"
import { downloadJSON } from "@/lib/sketches"
const GraphCanvas = dynamic(() => import("./graph-canvas").then((module) => module.GraphCanvas), { ssr: false })

function Presentation({ value }: { value: TeachingView }) {
  const [selected, setSelected] = useState(value.selected), [mode, setMode] = useState(value.mode)
  const node = value.graph.nodes.find((item) => item.id === selected)!
  const label = (id: string) => value.graph.nodes.find((item) => item.id === id)?.label.replace(/^[Mm]:/, "") || id
  return <article className="teaching-presentation"><header><p className="route-eyebrow">H·G / Teaching view · captured presentation</p><h1>{value.title}</h1><RouteMotif /><p className="curated-explanation">{value.explanation || "No author explanation was added. Use the route order and relationship evidence below to guide discussion."}</p><ContextSummary value={value.music} /><p className="capture-source">Source: {value.source} · {new Date(value.capturedAt).toLocaleString()} · format version 1. This is a snapshot, not a live corpus query.</p></header>
    <div className="action-row"><button type="button" aria-pressed={mode === "canvas"} onClick={() => setMode("canvas")}>3D atlas</button><button type="button" aria-pressed={mode === "list"} onClick={() => setMode("list")}>List view</button><button type="button" onClick={() => window.print()}>Print teaching notes</button><button type="button" onClick={() => downloadJSON(value, "harmonic-teaching-view.json")}>Export captured view</button><Link href={`/explore?${writeProgression(new URLSearchParams(), value.music)}`}>Explore this musical context</Link></div>
    <details><summary>Captured settings</summary><p>Center: {label(value.root)} · context: {value.filters.context} · neighborhood probability ≥ {value.filters.minProb} · tint: {value.tint === "none" ? "node type" : value.tint}</p><p>Relationships: {value.filters.edgeTypes.join(", ") || "All"}. Positions and camera are captured when the source was in 3D; List captures open as text first.</p></details>
    {value.path && <ol className="route-steps" aria-label="Route steps">{value.path.nodes.map((id, index) => <li key={`${id}:${index}`}><button type="button" onClick={() => setSelected(id)} aria-pressed={selected === id}><span>{index + 1}</span><strong>{label(id)}</strong><small>{index === 0 ? "Start" : index === value.path!.nodes.length - 1 ? "Destination" : "Step"}</small></button>{index < value.path!.nodes.length - 1 && <span aria-hidden="true">→</span>}</li>)}</ol>}
    <div className="teaching-scene">{mode === "canvas" ? <GraphCanvas graph={value.graph} selected={selected} colorAxis={value.tint} pathNodes={value.path?.nodes ?? []} pathEdges={value.path?.edges.map(edgeKey) ?? []} onSelect={setSelected} initialView={value.view} onListView={() => setMode("list")} /> : <div className="teaching-node-list" aria-label="Captured nodes">{value.graph.nodes.map((item) => <button type="button" key={item.id} onClick={() => setSelected(item.id)} aria-pressed={selected === item.id}>{label(item.id)}</button>)}</div>}<GraphLegend axis={value.tint} types={value.graph.nodes.map((item) => item.type)} /></div>
    <section className="teaching-inspector" aria-label="Teaching explanation"><h2>{label(selected)}{value.chord?.nodeId === selected && value.chord.key === value.music.key ? ` · ${value.chord.label}` : ""}</h2><p>{functionExplanation(selected)}</p>{value.chord?.nodeId !== selected && <p>No chord-name realization was captured for this node. The function label remains available.</p>}<p>Selected node type: {node.type}. {value.source === "sample" ? "This sample has no live corpus counts." : "Counts and probabilities below were captured at the stated time."}</p><details><summary>Node properties and provenance</summary><pre>{JSON.stringify(node.props, null, 2)}</pre></details></section>
    <section className="teaching-relationships"><h2>Relationships · accessible text equivalent</h2><p>Arrows describe source → destination. A transition connects observed harmonic functions; other relationship types express the named structural association. Probability is an observation-based measure when supplied, not a recommendation confidence.</p><div className="explorer-table-wrap" tabIndex={0} role="region" aria-label="Captured relationships table"><table><caption>{value.graph.nodes.length} captured nodes · {value.graph.edges.length} relationships</caption><thead><tr><th>From</th><th>To</th><th>Relationship</th><th>Context</th><th>Probability</th><th>Support</th><th>Route</th></tr></thead><tbody>{value.graph.edges.map((edge) => <tr key={edgeKey(edge)}><td>{label(edge.src)}</td><td>{label(edge.dst)}</td><td>{edge.type.replaceAll("_", " ").toLowerCase()}</td><td>{String(edge.context_id ?? edge.props.context_id ?? value.graph.context)}</td><td>{value.source === "sample" || edge.prob === null ? "Unavailable" : `${Math.round(edge.prob * 100)}%`}</td><td>{value.source === "sample" ? "Unavailable" : edge.count ?? "Unavailable"}</td><td>{value.path?.edges.some((item) => edgeKey(item) === edgeKey(edge)) ? "Active route" : ""}</td></tr>)}</tbody></table></div></section>
    {value.path && <section className="print-route"><h2>Route order</h2><ol>{value.path.nodes.map((id, index) => <li key={`${id}:${index}`}>{index + 1}. {label(id)}</li>)}</ol></section>}
    <section className="print-only"><h2>Captured settings and selected node</h2><p>Center: {label(value.root)} · Selected: {label(selected)} · Context: {value.filters.context} · Minimum neighborhood probability: {value.filters.minProb} · Tint: {value.tint}</p><p>Relationships: {value.filters.edgeTypes.join(", ") || "All"}</p><pre>{JSON.stringify(node.props, null, 2)}</pre></section>
    <p className="print-attribution">Harmonic Color Graph · Chordonomicon (Kantarelis et al., 2024), CC BY-NC 4.0. Relationship layout distance is not a similarity score. Explanation supplied by the presentation author.</p>
  </article>
}
export function TeachingPresentation() {
  const [revision, setRevision] = useState(0)
  const [value, setValue] = useState<TeachingView | null>(null), [error, setError] = useState("")
  useEffect(() => { const read = () => { try { setValue(parseTeachingHash(window.location.hash)); setRevision((current) => current + 1); setError("") } catch (caught) { setError(caught instanceof Error ? caught.message : "This teaching view could not be opened."); setValue(null) } }; const frame = requestAnimationFrame(read); window.addEventListener("hashchange", read); return () => { cancelAnimationFrame(frame); window.removeEventListener("hashchange", read) } }, [])
  return <main id="main-content" className="studio-page teaching-page">{error && <div className="request-error"><h1>Open a teaching view</h1><p role="alert">{error}</p><Link href="/explore">Prepare a new view in the atlas</Link></div>}<details className="presentation-import" open={!value}><summary>Import a teaching-view file</summary><label>Teaching view JSON<input type="file" accept="application/json,.json" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { if (file.size > 500_000) throw new Error("Teaching views support files up to 500 KB."); setValue(parseTeachingView(await file.text())); setRevision((current) => current + 1); setError("") } catch (caught) { setError(caught instanceof Error ? caught.message : "Invalid teaching file.") } event.target.value = "" }} /></label></details>{value && <Presentation key={revision} value={value} />}</main>
}
